// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/Frank-Macedo/19-DI/product"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeProductUseCase(db *sql.DB) *product.ProductUseCase {
	productRepositoryInterface := product.NewProductRepository(db)
	productUseCase := product.NewProductUseCase(productRepositoryInterface)
	return productUseCase
}

// wire.go:

var setRepositoryDependency = wire.NewSet(product.NewProductRepository)
